version: "3.9"

services:
  mqtt-broker:
    image: eclipse-mosquitto:latest
    container_name: mqtt_broker
    restart: always
    networks:
      - iot_network
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    ports:
      - "9001:9001" # WebSockets Port
      - "1883:1883" # MQTT Port

  mqtt-subscriber:
    build: ./mqtt-subscriber
    container_name: mqtt_subscriber
    restart: always
    depends_on:
      - mqtt-broker
      - flask-api
    networks:
      - iot_network
    environment:
      - MQTT_BROKER_HOST=mqtt-broker
      - MQTT_TOPIC=devices/events
      - DB_PATH=/data/iot_data.db
    volumes:
      - data:/data

  flask-api:
    build: ./flask-api
    container_name: flask_api
    restart: always
    depends_on:
      - mqtt-broker
    networks:
      - iot_network
    environment:
      - DB_PATH=/data/iot_data.db
    volumes:
      - data:/data
    ports:
      - "5000:5000"

networks:
  iot_network:
    driver: bridge

volumes:
  data:
    driver: local
