# Official Python base image
FROM python:3.9.21-alpine3.21

# Set the working directory inside the container
WORKDIR /app

# Copy the subscriber script and requirements
COPY requirements.txt .
COPY subscriber.py .
COPY MessageParser.py .
COPY Database.py .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Environment variables for the broker
ENV BROKER_HOST=mosquitto-broker

# Run the subscriber script
CMD ["python3", "subscriber.py"]
